version: '3.8'

services:
  database:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    networks:
      - mynet
volumes:
  postgres:
    driver: local
    
networks:
  mynet:
    driver: bridge  